site_name: B.2 Informatik Skript
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: ["docs"]
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
extra_css:
  - styles/extra.css
nav:
  - Allgemein:
    - Motivation: General/01_motivation.md
    - Roadmap: General/02_roadmap.md
  - Informatik:
    # - Projekte:
    #  - 2.Jahrgang: INFI/2AHWII/projects/01_project_relational-database.md
    - Lehrplan: INFI/00_lehrplan.md
    - Skript:
      - Datenbanken:
        - Einführung Datenbanken: INFI/2AHWII/01_why-databases.md
        - Datenbanksysteme: INFI/2AHWII/02_01_database-systems.md
        - Arbeiten mit Datenbanken: INFI/2AHWII/02_02_working-with-databases.md
        - MS SQL Server CLI Tutorial: INFI/2AHWII/02_03_mssql-cli.md
        - Einführung SQL: INFI/2AHWII/03_00_structured_query_language.md
        - Tabellen erstellen und löschen: INFI/2AHWII/03_01_sql_create_and_drop_command.md
        - Daten einfügen, ändern und löschen: INFI/2AHWII/03_02_sql_insert_command.md
        - Daten abfragen: INFI/2AHWII/03_03_sql_select_command.md
        # - 🧪 SQL Übung: INFI/2AHWII/04_exercise_movies.md
        - Tabellen ändern: INFI/2AHWII/03_04_sql_alter_command.md
        - Einführung Relationen: INFI/2AHWII/05_relations.md
        - Primärschlüssel: INFI/2AHWII/06_01_primary-key.md
        - Fremdschüssel - Beziehungen zwischen Tabellen: INFI/2AHWII/06_02_foreign_keys.md
        - Tabellen verbinden: INFI/2AHWII/07_sql_join_command.md
        - Kardinalitäten: INFI/2AHWII/09_cardinalities.md
        # - 🧪 Relationen Übung (1:n): INFI/2AHWII/08_01_exercise-1-to-n-relation.md
        # - 🧪 Relationen Übung (m:n): INFI/2AHWII/08_02_exercise-m-to-n-relation.md
        - Referenzielle Integrität: INFI/2AHWII/10_referential_integrity.md
        - Indizes: INFI/2AHWII/11_indizes.md
        - Datebankmodellierung: INFI/2AHWII/12_database-modelling.md
        - ER Modell und Diagram: INFI/2AHWII/13_er-modell.md
        - Normalformen: INFI/2AHWII/14_normal-forms.md
        - Aggregation und Gruppierung: INFI/2AHWII/16_aggregat-and-grouping.md
      - Geschätsprozessmodellierung:
        - Einführung Geschäftsprozesse: INFI/5AHWII/01_intro-business-process.md
        - Warum Geschäftsprozessmodellierung: INFI/5AHWII/02_why-business-process-modelling.md
        - Geschäftsprozessmodellierungsprachen: INFI/5AHWII/03_overview-business-process-models.md
        - BPMN 2.0 Grundlagen: INFI/5AHWII/04_intro-bpmn.md
  - SWP - Web:
    - Lehrplan:
      - 2.Jahrgang: SWP/WEB/2AHWII/00_lehrplan.md
      - 4.Jahrgang: SWP/WEB/4AHWII/00_lehrplan.md
    - Projekte:
      - 2.Jahrgang: SWP/WEB/2AHWII/projects/01_project_static-website.md
    - Skript - 2.Jahrgang:
      - Einführung in HTML: SWP/WEB/2AHWII/01_intro-web.md
      - HTML Grundstruktur und Tags: SWP/WEB/2AHWII/02_00_html-tags.md
      - Medien einbinden: SWP/WEB/2AHWII/02_01_medien.md
      - Einführung in CSS: SWP/WEB/2AHWII/03_00_intro-css.md
      - Farbwerte in CSS: SWP/WEB/2AHWII/03_01_colors.md
      - Einheiten in CSS: SWP/WEB/2AHWII/03_02_units.md
      - 🧪 Übung - Lebenslauf: SWP/WEB/2AHWII/04_exercise_my-cv.md
      - Gruppieren von Tags: SWP/WEB/2AHWII/05_div-tag.md
      - CSS Box Modell: SWP/WEB/2AHWII/06_00_css-box-modell.md
      - Schriftgestaltung in CSS: SWP/WEB/2AHWII/06_01_css-fonts.md
      - Positionierung in CSS: SWP/WEB/2AHWII/06_02_css-positioning.md
      - Layouts in CSS: SWP/WEB/2AHWII/06_layouts-with-css.md
      - 🧪 Übung - Flexbox: SWP/WEB/2AHWII/07_exercise_flexbox-coding-fantasy.md
      - CSS Cheatsheet: SWP/WEB/2AHWII/08_css-cheatsheet.md
      - CSS Background: SWP/WEB/2AHWII/09_css-background.md
      - Transition und Effects: SWP/WEB/2AHWII/10_transition-and-effects.md
      - Responsive Design: SWP/WEB/2AHWII/11_responsive-design.md
      - Semantisches HTML: SWP/WEB/2AHWII/12_semantisches-html.md
      - CSS Variablen: SWP/WEB/2AHWII/13_css-variablen.md
    - Skript - 3.Jahrgang:
      - Einführung in JavaScript: SWP/WEB/3AHWII/01_JS-fundamentals.md
      - DOM Manipulation und Events: SWP/WEB/3AHWII/02_dom-manipulation-and-events.md
      - Einführung in TypeScript: SWP/WEB/3AHWII/03_typescript-intro.md
      - TypeScript installieren: SWP/WEB/3AHWII/04_install-typescript.md
      - TypeScript benutzen: SWP/WEB/3AHWII/05_typescript-usage.md
  - SWP - Programmieren:
    - Lehrplan:
      - 2.Jahrgang: SWP/PR/2AHWII/00_lehrplan.md
      - 3.Jahrgang: SWP/PR/3AHWII/00_lehrplan.md
      - 4.Jahrgang: SWP/PR/4AHWII/00_lehrplan.md
    - Projekte:
      - 3.Jahrgang: 
        - Hangman: SWP/PR/3AHWII/projects/01_project_hangman.md
        - TicTacToe: SWP/PR/3AHWII/projects/02_project_tic-tac-toe.md
    - Skript - 2.Jahrgang:
      - Einführung in die stukturierte Programmierung: SWP/PR/2AHWII/01_intro-structured-programming.md
      - Erstes Programm: SWP/PR/2AHWII/02_first-program.md
      - IDE - Integrated Development Environment: SWP/PR/2AHWII/03_ide.md
      - dotnet vs C#: SWP/PR/2AHWII/04_dotnet-vs-csharp.md
      - Variablen und Datentypen: SWP/PR/2AHWII/05_variables-and-datatypes.md
      - Operatoren: SWP/PR/2AHWII/06_operators.md
      - Ein- und Ausgabe: SWP/PR/2AHWII/06_in-and-output.md
      - Kontrollstrukturen: SWP/PR/2AHWII/07_control-structures.md
      - Schleifen: SWP/PR/2AHWII/08_loops.md
      - Funktionen: SWP/PR/2AHWII/09_functions.md
      - Using Direktive und Bibliotheken: SWP/PR/2AHWII/09_using-and-libraries.md
      - Arrays und Listen: SWP/PR/2AHWII/10_arrays.md
      - Strings: SWP/PR/2AHWII/11_strings.md
    - Skript - 3.Jahrgang:
      - Struct: SWP/PR/2AHWII/12_structs.md
      # - Standardalgorithmen: SWP/PR/2AHWII/13_basic-algorithms.md
      - Einführung OOP: SWP/PR/3AHWII/01_intro-oop.md
      - Implizite Typinferenz (var): SWP/PR/3AHWII/02_var-keyword.md 
      - Properties in C#: SWP/PR/3AHWII/03_properties.md
      - Vererbung und Polymorphismus: SWP/PR/3AHWII/04_inheritence-and-polymorphysm.md
      - Interfaces: SWP/PR/3AHWII/05_interfaces.md
      - Collections: SWP/PR/3AHWII/06_collections.md
      - Graphical User Interfaces: SWP/PR/3AHWII/12_dotnet-guis.md
  - SWP - Projektmanagement:
    - Lehrplan:
      - 3.Jahrgang: SWP/PM/3AHWII/00_lehrplan.md
      - 4.Jahrgang: SWP/PM/4AHWII/00_lehrplan.md
    - Projekte:
      - 3.Jahrgang: SWP/PM/3AHWII/projects/01_project_create-sw-project-in-teams.md
      - 4.Jahrgang: SWP/PM/4AHWII/projects/01_project_implement-sw-project-in-teams.md
    - Skript - 3.Jahrgang:
      - Modellierung in der Softwareentwicklung: SWP/PM/3AHWII/01_modelling-intro.md
      - UML Klassendiagram: SWP/PM/3AHWII/02_modelling-class-diagram.md
      - UML Use-Case-Diagram: SWP/PM/3AHWII/03_use-case-diagram.md
      - UML Sequenzdiagram: SWP/PM/3AHWII/04_sequence-diagram.md
      - Flussdiagram: SWP/PM/3AHWII/05_flow-charts.md
      - Projektmanagement Grundlagen: SWP/PM/3AHWII/06_project-management-intro.md
    - Skript - 4.Jahrgang:
      - Softwareentwicklungsmodelle: SWP/PM/4AHWII/01_sw-engineering-models.md
      - Abschätzungsverfahren: SWP/PM/4AHWII/02_estimation-techniques.md
      - Anforderungsanalyse: SWP/PM/4AHWII/03_requirement-engineering.md
      - Design Patterns: SWP/PM/4AHWII/04_design-patterns.md
      - Testing: SWP/PM/4AHWII/05_quality-management.md
      - Projektmanagement: SWP/PM/4AHWII/06_project-management.md
      
  # - Fächerübergreifende Projekte:
  #   - NITFLEX - Film Verwaltung: CrossSubjectProjects/01_nitflex.md 