name: Build & Deploy MkDocs (GitHub Pages)

on:
  push:
    branches: [main]
    paths:
      - "script/docs/**"
      - "script/mkdocs.yml"
      - "slides/**"          # Slidev project
      - ".github/workflows/**"
      - "build_all.sh"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- MkDocs build ---
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site (in script/)
        working-directory: script
        run: mkdocs build --strict --site-dir ../_site

      # --- Slidev build ---
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Setup @antfu/ni
        run: npm i -g @antfu/ni
      - name: Install slide deps
        working-directory: slides
        run: nci
      - name: Build all decks (relative URLs)
        run: |
          bash build_all.sh
        env:
          MODE: absolute
          REPO_BASE: "/${{ github.event.repository.name }}/slides/"
          INPUT_ROOT: content/slides
          OUT_ROOT: dist
      - name: Merge outputs
        run: |
          mkdir -p _site/slides
          cp -r slides/content/slides/dist/* _site/slides/
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4